mobs_probabilities = { zombie = 1 } # { zombie = 0.9, giant = 0.1 }
mobs_extras = { mosquito = { 3 = 2, 4 = 2 } }
waves = [
    [
        5,
        4,
    ],
    [
        7,
        2,
    ],
    [
        8,
        3,
    ],
    [
        14,
        8,
    ],
    [
        "giant6",
        1,
    ],
    [
        3,
        2,
    ],
    [
        17,
        7,
    ],
    [
        5,
        1,
    ],
    [
        5,
        1,
    ],
    [
        5,
        1,
    ],
    [
        5,
        1,
    ],
    [
        5,
        8,
    ],
    [
        2,
        0.5,
    ],
    [
        8,
        4,
    ],
    [
        13,
        9,
    ],
    [
        3,
        0,
    ],
]
special_waves = { giant6 = { zombie = 6 } } # { giant = 6 } }
